let printMetaData = {
  unit: "px",
  pageWidth: "864",
  pageHeight: "624",
  title: "安全培训合格证书",
  pages: [
    {
      title: "安全培训合格证书-版面1",
      components: [
        {
          top: "458",
          left: "158",
          w: "210",
          h: "20",
          remark: "发证日期",
          val: "",
          type: "date",
        },
        {
          type: "date-range",
          start: {
            components: [
              {
                top: "502",
                left: "129",
                w: "34",
                h: "20",
                remark: "年份",
                val: "",
                type: "year",
              },
              {
                top: "502",
                left: "182",
                w: "22",
                h: "20",
                remark: "月",
                val: "",
                type: "month",
              },
              {
                top: "502",
                left: "221",
                w: "22",
                h: "20",
                remark: "日",
                val: "",
                type: "day",
              },
            ],
          },
          end: {
            components: [
              {
                top: "502",
                left: "272",
                w: "34",
                h: "20",
                remark: "年",
                val: "",
                type: "year",
              },
              {
                top: "502",
                left: "322",
                w: "22",
                h: "20",
                remark: "月",
                val: "",
                type: "month",
              },
              {
                top: "502",
                left: "358",
                w: "22",
                h: "20",
                remark: "日",
                val: "",
                type: "day",
              },
            ],
          },
        },
        {
          top: "546",
          left: "164",
          w: "190",
          h: "20",
          remark: "证书编号",
          val: "",
          type: "input",
        },
        {
          top: "133",
          left: "617",
          w: "200",
          h: "20",
          remark: "单位",
          val: "",
          type: "select",
          dictcode: "",
        },
        {
          top: "179",
          left: "617",
          w: "200",
          h: "20",
          remark: "姓名",
          val: "",
          type: "input",
        },
        {
          top: "228",
          left: "617",
          w: "200",
          h: "20",
          remark: "性别",
          val: "",
          type: "select",
          dictcode: "",
        },
        {
          top: "278",
          left: "617",
          w: "200",
          h: "20",
          remark: "职称",
          val: "",
          type: "select",
          dictcode: "",
        },
        {
          top: "326",
          left: "617",
          w: "200",
          h: "20",
          remark: "文化程度",
          val: "",
          type: "select",
          dictcode: "",
        },
        {
          top: "376",
          left: "617",
          w: "200",
          h: "20",
          remark: "身份证号",
          val: "",
          type: "input",
        },
        {
          top: "425",
          left: "617",
          w: "200",
          h: "20",
          remark: "单位类型",
          val: "",
          type: "select",
          dictcode: "",
        },
        {
          top: "473",
          left: "617",
          w: "200",
          h: "20",
          remark: "资格类型",
          val: "",
          type: "select",
          dictcode: "",
        },
      ],
    },

    {
      title: "安全培训合格证书-版面2",
      components: [
        {
          type: "date-range",
          start: {
            components: [
              {
                top: "119",
                left: "134",
                w: "34",
                h: "20",
                remark: "年",
                val: "",
              },
              {
                top: "119",
                left: "189",
                w: "22",
                h: "20",
                remark: "月",
                val: "",
              },
              {
                top: "119",
                left: "222",
                w: "22",
                h: "20",
                remark: "日",
                val: "",
              },
            ],
          },
          end: {
            components: [
              {
                top: "119",
                left: "270",
                w: "34",
                h: "20",
                remark: "年",
                val: "",
              },
              {
                top: "119",
                left: "323",
                w: "22",
                h: "20",
                remark: "月",
                val: "",
              },
              {
                top: "119",
                left: "356",
                w: "22",
                h: "20",
                remark: "日",
                val: "",
              },
            ],
          },
        },

        {
          type: "table",
          rows: [
            {
              components: [
                {
                  top: "192",
                  left: "75",
                  w: "22",
                  h: "20",
                  remark: "0-0",
                  val: "",
                },
                {
                  top: "185",
                  left: "105",
                  w: "110",
                  h: "33",
                  remark: "0-1",
                  val: "",
                },
                {
                  top: "192",
                  left: "227",
                  w: "38",
                  h: "20",
                  remark: "0-2",
                  val: "",
                },
                {
                  top: "192",
                  left: "278",
                  w: "38",
                  h: "20",
                  remark: "0-3",
                  val: "",
                },
                {
                  top: "185",
                  left: "322",
                  w: "65",
                  h: "33",
                  remark: "0-4",
                  val: "",
                },
              ],
            },

            {
              components: [
                {
                  top: "232",
                  left: "75",
                  w: "22",
                  h: "20",
                  remark: "1-0",
                  val: "",
                },
                {
                  top: "224",
                  left: "105",
                  w: "110",
                  h: "33",
                  remark: "1-1",
                  val: "",
                },
                {
                  top: "232",
                  left: "227",
                  w: "38",
                  h: "20",
                  remark: "1-2",
                  val: "",
                },
                {
                  top: "233",
                  left: "278",
                  w: "38",
                  h: "20",
                  remark: "1-3",
                  val: "",
                },
                {
                  top: "223",
                  left: "322",
                  w: "65",
                  h: "33",
                  remark: "1-4",
                  val: "",
                },
              ],
            },

            {
              components: [
                {
                  top: "271",
                  left: "75",
                  w: "22",
                  h: "20",
                  remark: "2-0",
                  val: "",
                },
                {
                  top: "264",
                  left: "105",
                  w: "110",
                  h: "33",
                  remark: "2-1",
                  val: "",
                },
                {
                  top: "271",
                  left: "227",
                  w: "38",
                  h: "20",
                  remark: "2-2",
                  val: "",
                },
                {
                  top: "271",
                  left: "278",
                  w: "38",
                  h: "20",
                  remark: "2-3",
                  val: "",
                },
                {
                  top: "262",
                  left: "322",
                  w: "65",
                  h: "33",
                  remark: "2-4",
                  val: "",
                },
              ],
            },
            {
              components: [
                {
                  top: "311",
                  left: "75",
                  w: "22",
                  h: "20",
                  remark: "3-0",
                  val: "",
                },
                {
                  top: "303",
                  left: "105",
                  w: "110",
                  h: "33",
                  remark: "3-1",
                  val: "",
                },
                {
                  top: "310",
                  left: "227",
                  w: "38",
                  h: "20",
                  remark: "3-2",
                  val: "",
                },
                {
                  top: "310",
                  left: "278",
                  w: "38",
                  h: "20",
                  remark: "3-3",
                  val: "",
                },
                {
                  top: "303",
                  left: "322",
                  w: "65",
                  h: "33",
                  remark: "3-4",
                  val: "",
                },
              ],
            },
            {
              components: [
                {
                  top: "348",
                  left: "75",
                  w: "22",
                  h: "20",
                  remark: "4-0",
                  val: "",
                },
                {
                  top: "341",
                  left: "105",
                  w: "110",
                  h: "33",
                  remark: "4-1",
                  val: "",
                },
                {
                  top: "348",
                  left: "227",
                  w: "38",
                  h: "20",
                  remark: "4-2",
                  val: "",
                },
                {
                  top: "348",
                  left: "278",
                  w: "38",
                  h: "20",
                  remark: "4-3",
                  val: "",
                },
                {
                  top: "343",
                  left: "322",
                  w: "65",
                  h: "33",
                  remark: "4-4",
                  val: "",
                },
              ],
            },
            {
              components: [
                {
                  top: "388",
                  left: "75",
                  w: "22",
                  h: "20",
                  remark: "5-0",
                  val: "",
                },
                {
                  top: "380",
                  left: "105",
                  w: "110",
                  h: "33",
                  remark: "5-1",
                  val: "",
                },
                {
                  top: "389",
                  left: "227",
                  w: "38",
                  h: "20",
                  remark: "5-2",
                  val: "",
                },
                {
                  top: "389",
                  left: "278",
                  w: "38",
                  h: "20",
                  remark: "5-3",
                  val: "",
                },
                {
                  top: "381",
                  left: "322",
                  w: "65",
                  h: "33",
                  remark: "5-4",
                  val: "",
                },
              ],
            },
            {
              components: [
                {
                  top: "428",
                  left: "75",
                  w: "22",
                  h: "20",
                  remark: "6-0",
                  val: "",
                },
                {
                  top: "420",
                  left: "105",
                  w: "110",
                  h: "33",
                  remark: "6-1",
                  val: "",
                },
                {
                  top: "427",
                  left: "227",
                  w: "38",
                  h: "20",
                  remark: "6-2",
                  val: "",
                },
                {
                  top: "427",
                  left: "278",
                  w: "38",
                  h: "20",
                  remark: "6-3",
                  val: "",
                },
                {
                  top: "421",
                  left: "322",
                  w: "65",
                  h: "33",
                  remark: "6-4",
                  val: "",
                },
              ],
            },
            {
              components: [
                {
                  top: "470",
                  left: "75",
                  w: "22",
                  h: "20",
                  remark: "7-0",
                  val: "",
                },
                {
                  top: "459",
                  left: "105",
                  w: "110",
                  h: "33",
                  remark: "7-1",
                  val: "",
                },
                {
                  top: "466",
                  left: "227",
                  w: "38",
                  h: "20",
                  remark: "7-2",
                  val: "",
                },
                {
                  top: "466",
                  left: "278",
                  w: "38",
                  h: "20",
                  remark: "7-3",
                  val: "",
                },
                {
                  top: "459",
                  left: "322",
                  w: "65",
                  h: "33",
                  remark: "7-4",
                  val: "",
                },
              ],
            },
            {
              components: [
                {
                  top: "507",
                  left: "75",
                  w: "22",
                  h: "20",
                  remark: "8-0",
                  val: "",
                },
                {
                  top: "497",
                  left: "105",
                  w: "110",
                  h: "33",
                  remark: "8-1",
                  val: "",
                },
                {
                  top: "503",
                  left: "227",
                  w: "38",
                  h: "20",
                  remark: "8-2",
                  val: "",
                },
                {
                  top: "504",
                  left: "278",
                  w: "38",
                  h: "20",
                  remark: "8-3",
                  val: "",
                },
                {
                  top: "497",
                  left: "322",
                  w: "65",
                  h: "33",
                  remark: "8-4",
                  val: "",
                },
              ],
            },
          ],
        },

        {
          type: "date-range",
          start: {
            components: [
              {
                top: "119",
                left: "579",
                w: "34",
                h: "20",
                remark: "年",
                val: "",
              },
              {
                top: "119",
                left: "629",
                w: "22",
                h: "20",
                remark: "月",
                val: "",
              },
              {
                top: "119",
                left: "662",
                w: "22",
                h: "20",
                remark: "日",
                val: "",
              },
            ],
          },
          end: {
            components: [
              {
                top: "119",
                left: "715",
                w: "34",
                h: "20",
                remark: "年",
                val: "",
              },
              {
                top: "119",
                left: "763",
                w: "22",
                h: "20",
                remark: "月",
                val: "",
              },
              {
                top: "119",
                left: "796",
                w: "22",
                h: "20",
                remark: "日",
                val: "",
              },
            ],
          },
        },

        {
          type: "table",
          rows: [
            {
              components: [
                {
                  top: "192",
                  left: "515",
                  w: "22",
                  h: "20",
                  remark: "0-0",
                  val: "",
                },
                {
                  top: "185",
                  left: "545",
                  w: "110",
                  h: "33",
                  remark: "0-1",
                  val: "",
                },
                {
                  top: "192",
                  left: "667",
                  w: "38",
                  h: "20",
                  remark: "0-2",
                  val: "",
                },
                {
                  top: "192",
                  left: "718",
                  w: "38",
                  h: "20",
                  remark: "0-3",
                  val: "",
                },
                {
                  top: "185",
                  left: "762",
                  w: "65",
                  h: "33",
                  remark: "0-4",
                  val: "",
                },
              ],
            },
            {
              components: [
                {
                  top: "232",
                  left: "515",
                  w: "22",
                  h: "20",
                  remark: "1-0",
                  val: "",
                },
                {
                  top: "224",
                  left: "545",
                  w: "110",
                  h: "33",
                  remark: "1-1",
                  val: "",
                },
                {
                  top: "232",
                  left: "667",
                  w: "38",
                  h: "20",
                  remark: "1-2",
                  val: "",
                },
                {
                  top: "233",
                  left: "718",
                  w: "38",
                  h: "20",
                  remark: "1-3",
                  val: "",
                },
                {
                  top: "223",
                  left: "762",
                  w: "65",
                  h: "33",
                  remark: "1-4",
                  val: "",
                },
              ],
            },
            {
              components: [
                {
                  top: "271",
                  left: "515",
                  w: "22",
                  h: "20",
                  remark: "2-0",
                  val: "",
                },
                {
                  top: "264",
                  left: "545",
                  w: "110",
                  h: "33",
                  remark: "2-1",
                  val: "",
                },
                {
                  top: "271",
                  left: "667",
                  w: "38",
                  h: "20",
                  remark: "2-2",
                  val: "",
                },
                {
                  top: "271",
                  left: "718",
                  w: "38",
                  h: "20",
                  remark: "2-3",
                  val: "",
                },
                {
                  top: "262",
                  left: "762",
                  w: "65",
                  h: "33",
                  remark: "2-4",
                  val: "",
                },
              ],
            },
            {
              components: [
                {
                  top: "311",
                  left: "515",
                  w: "22",
                  h: "20",
                  remark: "3-0",
                  val: "",
                },
                {
                  top: "303",
                  left: "545",
                  w: "110",
                  h: "33",
                  remark: "3-1",
                  val: "",
                },
                {
                  top: "310",
                  left: "667",
                  w: "38",
                  h: "20",
                  remark: "3-2",
                  val: "",
                },
                {
                  top: "310",
                  left: "718",
                  w: "38",
                  h: "20",
                  remark: "3-3",
                  val: "",
                },
                {
                  top: "303",
                  left: "762",
                  w: "65",
                  h: "33",
                  remark: "3-4",
                  val: "",
                },
              ],
            },
            {
              components: [
                {
                  top: "348",
                  left: "515",
                  w: "22",
                  h: "20",
                  remark: "4-0",
                  val: "",
                },
                {
                  top: "341",
                  left: "545",
                  w: "110",
                  h: "33",
                  remark: "4-1",
                  val: "",
                },
                {
                  top: "348",
                  left: "667",
                  w: "38",
                  h: "20",
                  remark: "4-2",
                  val: "",
                },
                {
                  top: "348",
                  left: "718",
                  w: "38",
                  h: "20",
                  remark: "4-3",
                  val: "",
                },
                {
                  top: "343",
                  left: "762",
                  w: "65",
                  h: "33",
                  remark: "4-4",
                  val: "",
                },
              ],
            },
            {
              components: [
                {
                  top: "388",
                  left: "515",
                  w: "22",
                  h: "20",
                  remark: "5-0",
                  val: "",
                },
                {
                  top: "380",
                  left: "545",
                  w: "110",
                  h: "33",
                  remark: "5-1",
                  val: "",
                },
                {
                  top: "389",
                  left: "667",
                  w: "38",
                  h: "20",
                  remark: "5-2",
                  val: "",
                },
                {
                  top: "389",
                  left: "718",
                  w: "38",
                  h: "20",
                  remark: "5-3",
                  val: "",
                },
                {
                  top: "381",
                  left: "762",
                  w: "65",
                  h: "33",
                  remark: "5-4",
                  val: "",
                },
              ],
            },
            {
              components: [
                {
                  top: "428",
                  left: "515",
                  w: "22",
                  h: "20",
                  remark: "6-0",
                  val: "",
                },
                {
                  top: "420",
                  left: "545",
                  w: "110",
                  h: "33",
                  remark: "6-1",
                  val: "",
                },
                {
                  top: "427",
                  left: "667",
                  w: "38",
                  h: "20",
                  remark: "6-2",
                  val: "",
                },
                {
                  top: "427",
                  left: "718",
                  w: "38",
                  h: "20",
                  remark: "6-3",
                  val: "",
                },
                {
                  top: "421",
                  left: "762",
                  w: "65",
                  h: "33",
                  remark: "6-4",
                  val: "",
                },
              ],
            },
          ],
        },

        {
          type: "date",
          components: [
            {
              top: "565",
              left: "696",
              w: "34",
              h: "20",
              remark: "年",
              val: "",
            },
            {
              top: "565",
              left: "751",
              w: "22",
              h: "20",
              remark: "月",
              val: "",
            },
            {
              top: "565",
              left: "796",
              w: "22",
              h: "20",
              remark: "日",
              val: "",
            },
          ],
        },
      ],
    },

    {
      title: "安全培训合格证书-版面3",
      components: [
        {
          type: "date-range",
          start: {
            components: [
              {
                top: "119",
                left: 134,
                w: "34",
                h: "20",
                remark: "年",
                val: "",
                type: "year",
              },
              {
                top: "119",
                left: 184,
                w: "22",
                h: "20",
                remark: "月",
                val: "",
                type: "month",
              },
              {
                top: "119",
                left: 217,
                w: "22",
                h: "20",
                remark: "日",
                val: "",
                type: "day",
              },
            ],
          },
          end: {
            components: [
              {
                top: "119",
                left: 270,
                w: "34",
                h: "20",
                remark: "年",
                val: "",
                type: "year",
              },
              {
                top: "119",
                left: 318,
                w: "22",
                h: "20",
                remark: "月",
                val: "",
                type: "month",
              },
              {
                top: "119",
                left: 351,
                w: "22",
                h: "20",
                remark: "日",
                val: "",
                type: "day",
              },
            ],
          },
        },
        {
          type: "table",
          rows: [
            {
              components: [
                {
                  top: "192",
                  left: 70,
                  w: "22",
                  h: "20",
                  remark: "0-0",
                  val: "",
                },
                {
                  top: "185",
                  left: 100,
                  w: "110",
                  h: "33",
                  remark: "0-1",
                  val: "",
                },
                {
                  top: "192",
                  left: 222,
                  w: "38",
                  h: "20",
                  remark: "0-2",
                  val: "",
                },
                {
                  top: "192",
                  left: 273,
                  w: "38",
                  h: "20",
                  remark: "0-3",
                  val: "",
                },
                {
                  top: "185",
                  left: 317,
                  w: "65",
                  h: "33",
                  remark: "0-4",
                  val: "",
                },
              ],
            },
            {
              components: [
                {
                  top: "232",
                  left: 70,
                  w: "22",
                  h: "20",
                  remark: "1-0",
                  val: "",
                },
                {
                  top: "224",
                  left: 100,
                  w: "110",
                  h: "33",
                  remark: "1-1",
                  val: "",
                },
                {
                  top: "232",
                  left: 222,
                  w: "38",
                  h: "20",
                  remark: "1-2",
                  val: "",
                },
                {
                  top: "233",
                  left: 273,
                  w: "38",
                  h: "20",
                  remark: "1-3",
                  val: "",
                },
                {
                  top: "223",
                  left: 317,
                  w: "65",
                  h: "33",
                  remark: "1-4",
                  val: "",
                },
              ],
            },
            {
              components: [
                {
                  top: "271",
                  left: 70,
                  w: "22",
                  h: "20",
                  remark: "2-0",
                  val: "",
                },
                {
                  top: "264",
                  left: 100,
                  w: "110",
                  h: "33",
                  remark: "2-1",
                  val: "",
                },
                {
                  top: "271",
                  left: 222,
                  w: "38",
                  h: "20",
                  remark: "2-2",
                  val: "",
                },
                {
                  top: "271",
                  left: 273,
                  w: "38",
                  h: "20",
                  remark: "2-3",
                  val: "",
                },
                {
                  top: "262",
                  left: 317,
                  w: "65",
                  h: "33",
                  remark: "2-4",
                  val: "",
                },
              ],
            },
            {
              components: [
                {
                  top: "311",
                  left: 70,
                  w: "22",
                  h: "20",
                  remark: "3-0",
                  val: "",
                },
                {
                  top: "303",
                  left: 100,
                  w: "110",
                  h: "33",
                  remark: "3-1",
                  val: "",
                },
                {
                  top: "310",
                  left: 222,
                  w: "38",
                  h: "20",
                  remark: "3-2",
                  val: "",
                },
                {
                  top: "310",
                  left: 273,
                  w: "38",
                  h: "20",
                  remark: "3-3",
                  val: "",
                },
                {
                  top: "303",
                  left: 317,
                  w: "65",
                  h: "33",
                  remark: "3-4",
                  val: "",
                },
              ],
            },
            {
              components: [
                {
                  top: "348",
                  left: 70,
                  w: "22",
                  h: "20",
                  remark: "4-0",
                  val: "",
                },
                {
                  top: "341",
                  left: 100,
                  w: "110",
                  h: "33",
                  remark: "4-1",
                  val: "",
                },
                {
                  top: "348",
                  left: 222,
                  w: "38",
                  h: "20",
                  remark: "4-2",
                  val: "",
                },
                {
                  top: "348",
                  left: 273,
                  w: "38",
                  h: "20",
                  remark: "4-3",
                  val: "",
                },
                {
                  top: "343",
                  left: 317,
                  w: "65",
                  h: "33",
                  remark: "4-4",
                  val: "",
                },
              ],
            },
            {
              components: [
                {
                  top: "388",
                  left: 70,
                  w: "22",
                  h: "20",
                  remark: "5-0",
                  val: "",
                },
                {
                  top: "380",
                  left: 100,
                  w: "110",
                  h: "33",
                  remark: "5-1",
                  val: "",
                },
                {
                  top: "389",
                  left: 222,
                  w: "38",
                  h: "20",
                  remark: "5-2",
                  val: "",
                },
                {
                  top: "389",
                  left: 273,
                  w: "38",
                  h: "20",
                  remark: "5-3",
                  val: "",
                },
                {
                  top: "381",
                  left: 317,
                  w: "65",
                  h: "33",
                  remark: "5-4",
                  val: "",
                },
              ],
            },
            {
              components: [
                {
                  top: "428",
                  left: 70,
                  w: "22",
                  h: "20",
                  remark: "6-0",
                  val: "",
                },
                {
                  top: "420",
                  left: 100,
                  w: "110",
                  h: "33",
                  remark: "6-1",
                  val: "",
                },
                {
                  top: "427",
                  left: 222,
                  w: "38",
                  h: "20",
                  remark: "6-2",
                  val: "",
                },
                {
                  top: "427",
                  left: 273,
                  w: "38",
                  h: "20",
                  remark: "6-3",
                  val: "",
                },
                {
                  top: "421",
                  left: 317,
                  w: "65",
                  h: "33",
                  remark: "6-4",
                  val: "",
                },
              ],
            },
          ],
        },
        {
          type: "date",
          components: [
            {
              top: "565",
              left: 251,
              w: "34",
              h: "20",
              remark: "年",
              val: "",
              type: "year",
            },
            {
              top: "565",
              left: 306,
              w: "22",
              h: "20",
              remark: "月",
              val: "",
              type: "month",
            },
            {
              top: "565",
              left: 351,
              w: "22",
              h: "20",
              remark: "日",
              val: "",
              type: "day",
            },
          ],
        },
        {
          top: "139",
          left: 491,
          w: "342",
          h: "442",
          remark: "备注",
          val: "",
          type: "input",
        },
      ],
    },

    {
      title: "安全培训合格证书-版面4",
      components: [
        {
          top: "139",
          left: 46,
          w: "342",
          h: "442",
          remark: "备注",
          val: "",
          type: "input",
        },
      ],
    },
  ],
};


export default printMetaData