export default {
  title: "版面3",
  name:'page3',
  bgimg:'http://81.68.204.177:9999/static/download/page3.png',
  components: [
    {
      top: "119",
      left: 134,
      w: "34",
      h: "20",
      remark: "年",
      val: "",
      type: "year",
    },
    {
      top: "119",
      left: 184,
      w: "22",
      h: "20",
      remark: "月",
      val: "",
      type: "month",
    },
    {
      top: "119",
      left: 217,
      w: "22",
      h: "20",
      remark: "日",
      val: "",
      type: "day",
    },

    {
      top: "119",
      left: 270,
      w: "34",
      h: "20",
      remark: "年",
      val: "",
      type: "year",
    },
    {
      top: "119",
      left: 318,
      w: "22",
      h: "20",
      remark: "月",
      val: "",
      type: "month",
    },
    {
      top: "119",
      left: 351,
      w: "22",
      h: "20",
      remark: "日",
      val: "",
      type: "day",
    },

    {
      top: "192",
      left: 70,
      w: "22",
      h: "20",
      remark: "0-0",
      val: "",
    },
    {
      top: "185",
      left: 100,
      w: "110",
      h: "33",
      remark: "0-1",
      val: "",
    },
    {
      top: "192",
      left: 222,
      w: "38",
      h: "20",
      remark: "0-2",
      val: "",
    },
    {
      top: "192",
      left: 273,
      w: "38",
      h: "20",
      remark: "0-3",
      val: "",
    },
    {
      top: "185",
      left: 317,
      w: "65",
      h: "33",
      remark: "0-4",
      val: "",
    },

    {
      top: "232",
      left: 70,
      w: "22",
      h: "20",
      remark: "1-0",
      val: "",
    },
    {
      top: "224",
      left: 100,
      w: "110",
      h: "33",
      remark: "1-1",
      val: "",
    },
    {
      top: "232",
      left: 222,
      w: "38",
      h: "20",
      remark: "1-2",
      val: "",
    },
    {
      top: "233",
      left: 273,
      w: "38",
      h: "20",
      remark: "1-3",
      val: "",
    },
    {
      top: "223",
      left: 317,
      w: "65",
      h: "33",
      remark: "1-4",
      val: "",
    },

    {
      top: "271",
      left: 70,
      w: "22",
      h: "20",
      remark: "2-0",
      val: "",
    },
    {
      top: "264",
      left: 100,
      w: "110",
      h: "33",
      remark: "2-1",
      val: "",
    },
    {
      top: "271",
      left: 222,
      w: "38",
      h: "20",
      remark: "2-2",
      val: "",
    },
    {
      top: "271",
      left: 273,
      w: "38",
      h: "20",
      remark: "2-3",
      val: "",
    },
    {
      top: "262",
      left: 317,
      w: "65",
      h: "33",
      remark: "2-4",
      val: "",
    },

    {
      top: "311",
      left: 70,
      w: "22",
      h: "20",
      remark: "3-0",
      val: "",
    },
    {
      top: "303",
      left: 100,
      w: "110",
      h: "33",
      remark: "3-1",
      val: "",
    },
    {
      top: "310",
      left: 222,
      w: "38",
      h: "20",
      remark: "3-2",
      val: "",
    },
    {
      top: "310",
      left: 273,
      w: "38",
      h: "20",
      remark: "3-3",
      val: "",
    },
    {
      top: "303",
      left: 317,
      w: "65",
      h: "33",
      remark: "3-4",
      val: "",
    },

    {
      top: "348",
      left: 70,
      w: "22",
      h: "20",
      remark: "4-0",
      val: "",
    },
    {
      top: "341",
      left: 100,
      w: "110",
      h: "33",
      remark: "4-1",
      val: "",
    },
    {
      top: "348",
      left: 222,
      w: "38",
      h: "20",
      remark: "4-2",
      val: "",
    },
    {
      top: "348",
      left: 273,
      w: "38",
      h: "20",
      remark: "4-3",
      val: "",
    },
    {
      top: "343",
      left: 317,
      w: "65",
      h: "33",
      remark: "4-4",
      val: "",
    },

    {
      top: "388",
      left: 70,
      w: "22",
      h: "20",
      remark: "5-0",
      val: "",
    },
    {
      top: "380",
      left: 100,
      w: "110",
      h: "33",
      remark: "5-1",
      val: "",
    },
    {
      top: "389",
      left: 222,
      w: "38",
      h: "20",
      remark: "5-2",
      val: "",
    },
    {
      top: "389",
      left: 273,
      w: "38",
      h: "20",
      remark: "5-3",
      val: "",
    },
    {
      top: "381",
      left: 317,
      w: "65",
      h: "33",
      remark: "5-4",
      val: "",
    },

    {
      top: "428",
      left: 70,
      w: "22",
      h: "20",
      remark: "6-0",
      val: "",
    },
    {
      top: "420",
      left: 100,
      w: "110",
      h: "33",
      remark: "6-1",
      val: "",
    },
    {
      top: "427",
      left: 222,
      w: "38",
      h: "20",
      remark: "6-2",
      val: "",
    },
    {
      top: "427",
      left: 273,
      w: "38",
      h: "20",
      remark: "6-3",
      val: "",
    },
    {
      top: "421",
      left: 317,
      w: "65",
      h: "33",
      remark: "6-4",
      val: "",
    },

    {
      top: "565",
      left: 251,
      w: "34",
      h: "20",
      remark: "年",
      val: "",
      type: "year",
    },
    {
      top: "565",
      left: 306,
      w: "22",
      h: "20",
      remark: "月",
      val: "",
      type: "month",
    },
    {
      top: "565",
      left: 351,
      w: "22",
      h: "20",
      remark: "日",
      val: "",
      type: "day",
    },
    {
      top: "139",
      left: 491,
      w: "342",
      h: "442",
      remark: "备注",
      val: "",
      type: "input",
    },
  ],
};
