export default {
    title: "安全培训合格证书-版面1",
    components: [
      {
        top: "458",
        left: "158",
        w: "210",
        h: "20",
        remark: "发证日期",
        val: "",
        type: "date",
        ext:{
          cmd:[' LODOP.SET_PRINT_STYLEA(0,"FontSize",7); ']
        }
      },

      {
        top: "502",
        left: "129",
        w: "34",
        h: "20",
        remark: "年份",
        val: "",
        type: "year",
      },
      {
        top: "502",
        left: "182",
        w: "22",
        h: "20",
        remark: "月",
        val: "",
        type: "month",
      },
      {
        top: "502",
        left: "221",
        w: "22",
        h: "20",
        remark: "日",
        val: "",
        type: "day",
      },

      {
        top: "502",
        left: "272",
        w: "34",
        h: "20",
        remark: "年",
        val: "",
        type: "year",
      },
      {
        top: "502",
        left: "322",
        w: "22",
        h: "20",
        remark: "月",
        val: "",
        type: "month",
      },
      {
        top: "502",
        left: "358",
        w: "22",
        h: "20",
        remark: "日",
        val: "",
        type: "day",
      },

      {
        top: "546",
        left: "164",
        w: "190",
        h: "20",
        remark: "证书编号",
        val: "",
        type: "input",
      },
      {
        top: "133",
        left: "617",
        w: "200",
        h: "20",
        remark: "单位",
        val: "",
        type: "select",
        dictcode: "",
      },
      {
        top: "179",
        left: "617",
        w: "200",
        h: "20",
        remark: "姓名",
        val: "",
        type: "input",
      },
      {
        top: "228",
        left: "617",
        w: "200",
        h: "20",
        remark: "性别",
        val: "",
        type: "select",
        dictcode: "",
      },
      {
        top: "278",
        left: "617",
        w: "200",
        h: "20",
        remark: "职称",
        val: "",
        type: "select",
        dictcode: "",
      },
      {
        top: "326",
        left: "617",
        w: "200",
        h: "20",
        remark: "文化程度",
        val: "",
        type: "select",
        dictcode: "",
      },
      {
        top: "376",
        left: "617",
        w: "200",
        h: "20",
        remark: "身份证号",
        val: "",
        type: "input",
      },
      {
        top: "425",
        left: "617",
        w: "200",
        h: "20",
        remark: "单位类型",
        val: "",
        type: "select",
        dictcode: "",
      },
      {
        top: "473",
        left: "617",
        w: "200",
        h: "20",
        remark: "资格类型",
        val: "",
        type: "select",
        dictcode: ""
      }
    ]
  }